version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:18.01.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run inndb_ruby-sample
          command: |
            ./test.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
