version: 2

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Run inndb_ruby-sample
          command: |
            ./test.sh

workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
